apiVersion: apps/v1
kind: Deployment
metadata:
  name: swift-bridge-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: swift-bridge-service
  template:
    metadata:
      labels:
        component: swift-bridge-service
        release: 2.50.1
    spec:
      containers:
        - name: swift-bridge
          image: index.docker.io/octopussolutionsengineering/ghu-swift-bridge:26.03.19222257
          ports:
            - name: http-route
              containerPort: 80
          env:
            - name: DATABASE_SERVER
              value: "pt-postgres-server-non-prod"
            - name: DATABASE_NAME
              value: "swift-bridge-db"
