apiVersion: apps/v1
kind: Deployment
metadata:
  name: instant-pay-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: instant-pay-gateway-service
  template:
    metadata:
      labels:
        component: instant-pay-gateway-service
        release: 2.33.4
    spec:
      containers:
        - name: instant-pay-gateway
          image: index.docker.io/octopussolutionsengineering/ghu-instant-pay-gateway:26.03.19221937
          ports:
            - name: http-route
              containerPort: 80
          env:
            - name: DATABASE_SERVER
              value: "pt-postgres-server-non-prod"
            - name: DATABASE_NAME
              value: "instant-pay-gateway-db"
