apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: pricing-frontend-service
  template:
    metadata:
      labels:
        component: pricing-frontend-service
    spec:
      containers:
        - name: pricing-frontend
          image: index.docker.io/octopussolutionsengineering/ghu-instant-pay-gateway:26.03.18222046
          ports:
            - name: http-route
              containerPort: 80
          env:
            - name: DATABASE_SERVER
              value: "development"
            - name: DATABASE_NAME
              value: "pricing-frontend"
