apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: pricing-database-service
  template:
    metadata:
      labels:
        component: pricing-database-service
        release: 1.2.4
    spec:
      containers:
        - name: pricing-database
          image: index.docker.io/octopussolutionsengineering/ghu-instant-pay-gateway:26.03.19182935
          ports:
            - name: http-route
              containerPort: 80
          env:
            - name: DATABASE_SERVER
              value: "development"
            - name: DATABASE_NAME
              value: "pricing-database"
